# Generated by Django 5.0 on 2023-12-24 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cecd220-b58b-4fb2-b3a6-6f669e46d7d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cecd220-b58b-4fb2-b3a6-6f669e46d7d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cecd220-b58b-4fb2-b3a6-6f669e46d7d9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6cecd220-b58b-4fb2-b3a6-6f669e46d7d9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
