# Generated by Django 5.0 on 2023-12-24 12:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_amenities_uid_alter_hotel_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('81168573-e1cc-43f3-8c92-1ee56317864f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('81168573-e1cc-43f3-8c92-1ee56317864f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('81168573-e1cc-43f3-8c92-1ee56317864f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('81168573-e1cc-43f3-8c92-1ee56317864f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
